spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ebuleje-dev/nttd-banking-config-repo.git
          default-label: main
          search-paths: '{application}'
          clone-on-start: true
          timeout: 15

          # Environment variables
          private-key: ${CONFIG_SSH_KEY:}
          passphrase: ${SSH_KEY_PASSPHRASE:}
